
CREATE TABLE GAMES(
  GID VARCHAR(4) PRIMARY KEY NOT NULL,
  GAME_NAME VARCHAR(17),
  MIN_PLAYERS INT,
  MAX_PLAYERS INT
);


CREATE TABLE PLAYER(
  PID VARCHAR(8) PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(10),
  LAST_NAME VARCHAR(16),
  GID VARCHAR(4),
  FOREIGN KEY(GID) references GAMES(GID)
);


CREATE TABLE PLAYER_TO_GAMES(
  PID VARCHAR(4) NOT NULL,
  GID VARCHAR(4) NOT NULL,
  LAST_PLAYED DATE,
  MINUTES_PLAYED INT
);


INSERT INTO GAMES VALUES('MN01', 'MONOPOLY', 2, 10);
INSERT INTO GAMES VALUES('CH01', 'CHESS', 2, 2);
INSERT INTO GAMES VALUES('CA22', 'CATAN', 2, 6);
INSERT INTO GAMES VALUES('EK09', 'EXPLODING KITTENS', 2, 5);

SELECT * FROM GAMES;


INSERT INTO PLAYER VALUES ('AE12', 'ALBERT', 'EINSTEIN', 'MN01');
INSERT INTO PLAYER VALUES ('GK12', 'GARY', 'KASPAROV', 'CH01');
INSERT INTO PLAYER VALUES ('SK01', 'SOPHIA', 'KETCHEN', 'CA22');
INSERT INTO PLAYER VALUES ('BK01', 'BRYCE', 'KETCHEN', 'EK09');


SELECT * FROM PLAYER;
