
CREATE TABLE GAMES(
  GID VARCHAR(4) PRIMARY KEY NOT NULL,
-- INSTRUCTIONS SAID VARCHAR(16) BUT MADE 17 TO ACCOUNT FOR THE LONGER GAME NAME GIVEN BELOW
  GAME_NAME VARCHAR(17),
  MIN_PLAYERS INT,
  MAX_PLAYERS INT
);


CREATE TABLE PLAYER(
  PID VARCHAR(8) PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(10),
  LAST_NAME VARCHAR(16),
  GID VARCHAR(4)
);


CREATE TABLE PLAYER_TO_GAMES(
  PID VARCHAR(4) NOT NULL,
  GID VARCHAR(4) NOT NULL,
  LAST_PLAYED DATE,
  MINUTES_PLAYED INT
);


INSERT INTO GAMES VALUES('MN01', 'MONOPOLY', 2, 10);
INSERT INTO GAMES VALUES('CH01', 'CHESS', 2, 2);
INSERT INTO GAMES VALUES('CA22', 'CATAN', 2, 6);
INSERT INTO GAMES VALUES('EK09', 'EXPLODING KITTENS', 2, 5);

SELECT * FROM GAMES;


INSERT INTO PLAYER VALUES ('AE12', 'ALBERT', 'EINSTEIN', 'MN01');
INSERT INTO PLAYER VALUES ('GK12', 'GARY', 'KASPAROV', 'CH01');
INSERT INTO PLAYER VALUES ('BF12', 'BOBBY', 'FISHER', 'CH01');
INSERT INTO PLAYER VALUES ('SK01', 'SOPHIA', 'KETCHEN', 'CA22');
INSERT INTO PLAYER VALUES ('BK01', 'BRYCE', 'KETCHEN', 'EK09');


SELECT * FROM PLAYER;

INSERT INTO PLAYER_TO_GAMES VALUES ('AE12', 'MN01', '10-OCT-2026', 25);
INSERT INTO PLAYER_TO_GAMES VALUES ('GK12', 'CH01', '12-NOV-2026', 59);
INSERT INTO PLAYER_TO_GAMES VALUES ('BF12', 'CH01', '28-DEC-2026', 21);



SELECT GID, MAX(MINUTES_PLAYED) 
FROM PLAYER_TO_GAMES
GROUP BY GID;
SELECT GID, MIN(MINUTES_PLAYED) 
FROM PLAYER_TO_GAMES
GROUP BY GID;
SELECT GID, COUNT(MINUTES_PLAYED) 
FROM PLAYER_TO_GAMES
GROUP BY GID;
SELECT GID, AVG(MINUTES_PLAYED) 
FROM PLAYER_TO_GAMES
GROUP BY GID;
