-- AUTHOR: SOPHIA KETCHEN

CREATE TABLE AUTHOR(
  A_Id VARCHAR(4) PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR2(16),
  MIDDLE_NAME VARCHAR2(16),
  LAST_NAME VARCHAR2(16) NOT NULL,
  GENRE_ID VARCHAR2(4) NOT NULL
  FOREIGN KEY (GENRE_ID) REFERENCES GENRE(G_ID)
);

CREATE TABLE GENRE(
  G_ID VARCHAR(4) PRIMARY KEY NOT NULL,
  GENRE_NAME VARCHAR(18) NOT NULL
);


INSERT INTO AUTHOR VALUES ('JVOL' ,'JULES', '', 'VERNE', 'SCIF');
INSERT INTO AUTHOR VALUES ('EP01', 'EDGAR', 'ALLEN', 'POE', 'HOR1');
INSERT INTO AUTHOR VALUES ('DB33', 'DAN', '', 'BROWN', 'SUSP');

INSERT INTO GENRE VALUES ('SCIF', 'SCIENCE FICTION');
INSERT INTO GENRE VALUES('HOR1', 'HORROR');
INSERT INTO GENRE VALUES('SUSP', 'SUSPENCE');
INSERT INTO GENRE VALUES('FANT', 'FANTASY');



SELECT * FROM AUTHOR;
SELECT * FROM GENRE;

SELECT FIRST_NAME, LAST_NAME, GENRE_NAME FROM AUTHOR, GENRE
WHERE AUTHOR.GENRE_ID = GENRE.G_ID;

SELECT FIRST_NAME, LAST_NAME, GENRE_NAME FROM AUTHOR A, GENRE G
WHERE A.GENRE_ID = G.G_ID;



