-- PART 1
-- Author: Sophia Ketchen
DROP TABLE IF EXISTS WORKERS;
DROP TABLE IF EXISTS DEPT;


CREATE TABLE Workers (
  WID varchar(6) NOT NULL,
  FIRST_NAME VARCHAR2(10),
  LAST_NAME VARCHAR2(10),
  JOB_TITLE VARCHAR2(16),
  SALARY decimal(8,2)
);

INSERT INTO Workers VALUES ('145AGT', 'ALAN', 'TREMAIN', 'CEO', 150000.00);
INSERT INTO Workers VALUES ('350CBA', 'CHARLES', 'ANTON', 'ACCOUNTANT', 7500.00);
INSERT INTO Workers VALUES ('357FRR', 'FRANK', 'ROBERTS', 'ACCOUNTANT', 68500.00);
INSERT INTO Workers VALUES ('907ARN', 'ANNE', 'NORRIS', 'CHEIF TECH OFFIC', 95000.00);
INSERT INTO Workers VALUES ('451WAW', 'WILLIAM', 'WARREN', 'ENGINEER', 82000.00);

SELECT * FROM Workers;


CREATE TABLE Dept (
  DID VARCHAR2(4) NOT NULL,
  DEPT_NAME VARCHAR2(15)
);

INSERT INTO Dept VALUES ('HRES', 'HUMAN RESOURCES');
INSERT INTO Dept VALUES ('ACCT', 'ACCOUNTING');
INSERT INTO Dept VALUES ('ADVR', 'ADVERTISING');
INSERT INTO Dept VALUES ('ADMN', 'ADMINISTRATION');
INSERT INTO Dept VALUES ('SALE', 'SALES');
INSERT INTO Dept VALUES ('LEGL', 'LEGAL');
INSERT INTO Dept VALUES ('PROP', 'REAL ESTATE');
INSERT INTO Dept VALUES ('TECH', 'TECH DEPARTMENT');



-- PART 2
INSERT INTO Workers VALUES ('162JMA','JONATHAN', 'ARNOLD', 'PROGRAMMER', 78000.00);

SELECT * FROM Workers;



-- PART 3
UPDATE Workers
SET Salary = 72000.00
WHERE WID = '357FRR';

SELECT * FROM Workers;



-- PART 4
ALTER TABLE WORKERS
    MODIFY JOB_TITLE varchar(18);

UPDATE Workers
SET JOB_TITLE = 'CHEIF TECH OFFICER'
WHERE WID = '907ARN';

SELECT * FROM Workers;


-- PART 5
UPDATE Workers
SET FIRST_NAME = 'WARREN' 
WHERE WID = '451WAW';

UPDATE Workers
SET LAST_NAME = 'WILLIAM'
WHERE WID = '451WAW';


SELECT * FROM Workers;
